version: 1
mtm:
  equity_source: runtime/account_runtime.json  # account_overview MTM equity source
  stale_seconds: 30
  stale_heartbeat_misses_for_flatten: 2

limits:
  # dynamic exposure cap recalculated on each tick from MTM equity unless explicit usd cap is set
  max_exposure_mode: dynamic        # dynamic | fixed_usd
  max_exposure_usd: 0               # used only if mode=fixed_usd
  max_exposure_pct_equity: 65       # used if mode=dynamic
  max_per_symbol_pct_equity: 45
  max_leverage: 1.5
  per_trade_risk_pct: 1.25
  daily_loss_limit_pct: 4.0

ops:
  kill_switch_persistent: true
  auto_flatten_on_daily_loss_breaker: true
  safe_start_flatten_if_breaker_active: true

audit:
  # 9-code taxonomy
  codes:
    - RISK_MAX_EXPOSURE
    - RISK_PER_SYMBOL
    - RISK_PER_TRADE
    - RISK_DAILY_LOSS
    - RISK_LEVERAGE
    - OPS_KILL_SWITCH
    - OPS_HEALTHZ_STALE
    - ML_VETO
    - API_ERROR

reload:
  enabled: true
