name: Aethelred CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optional dev tools if not in requirements.txt
          pip install pytest ruff mypy joblib matplotlib scikit-learn pyarrow

      - name: Lint - ruff
        run: |
          ruff check api tests_api || true
          # set to `|| exit 1` when you want hard failure on lint issues

      - name: Typecheck - mypy
        run: |
          mypy api tests_api

      - name: Unit and API tests
        env:
          PYTHONHASHSEED: "0"
        run: |
          pytest -q

      - name: ML smoke - stop_distance join only
        run: |
          # Only run the join with a tiny parquet if present
          if [ -f "data/ohlcv_smoke.parquet" ]; then
            python scripts/train_stop_distance_regressor_v1.py --ohlcv data/ohlcv_smoke.parquet --horizon 5 --save_joined reports/stop_distance_joined_smoke.csv
          else
            echo "Skipping ML smoke - no data/ohlcv_smoke.parquet"
          fi

      - name: Collect reports artifacts
        if: always()
        run: |
          mkdir -p artifacts
          [ -d reports ] && cp -r reports artifacts/reports || true
          [ -f reports/stop_distance_v1_calibration.png ] && cp reports/stop_distance_v1_calibration.png artifacts/ || true
          [ -f reports/stop_distance_v1_eval_summary.csv ] && cp reports/stop_distance_v1_eval_summary.csv artifacts/ || true
          [ -f reports/intent_veto_v1_summary.csv ] && cp reports/intent_veto_v1_summary.csv artifacts/ || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aethelred-${{ matrix.python-version }}-${{ github.sha }}
          path: artifacts
          if-no-files-found: ignore
