name: CI
on:
  push:
    branches: ["feat/**", "main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff mypy pytest
      - name: Ruff lint
        run: ruff check api
      - name: Ruff format check
        run: ruff format --check api
      - name: MyPy typecheck
        run: mypy api
      - name: Pytest
        run: pytest -q ./tests_api --cov=api --cov-report=term-missing:skip-covered --cov-report=xml:coverage.xml
